# Domain configration file in TOML format.
version = "1.0"
region = "ap-southeast-2"

[[buckets]]
name = "downloads"
region = "ap-southeast-2"
type = "fs"
pathname = "/downloads/"
public = true
encryption = ""

[[buckets]]
name = "movies"
region = "ap-southeast-2"
type = "fs"
pathname = "/movies/"
public = false
encryption = ""