#!/usr/bin/env bash
#
# stress-gate.sh - Run e2e-stress scenarios and gate on a committed baseline.
#
# Two of the stress scenarios fail against predastore today, so a bare exit
# status makes the suite unusable as a gate: it would be red from its first run
# and read by nobody. Against a baseline the question becomes the useful one —
# did something that used to survive stop surviving.
#
# Scenario granularity rather than assertion granularity, because e2e-stress.sh
# aborts on its first failed assertion and writes no result file when it does.
# An assertion-level baseline would have nothing to compare after a hard
# failure, which is exactly the case a gate exists for.
#
# Usage:
#   ./scripts/bench/stress-gate.sh                    # every baselined scenario
#   ./scripts/bench/stress-gate.sh freeze             # named scenarios only
#
# Environment:
#   STRESS_BASELINE        Baseline file (default: scripts/stress-baseline.txt)
#   STRESS_WRITE_BASELINE  Record outcomes here instead of gating
#   Everything e2e-stress.sh reads is passed through untouched.
#
set -uo pipefail

SCRIPT_DIR="$(cd "$(dirname "$(readlink -f "$0")")" && pwd -P)"
REPO_DIR="$(cd "$SCRIPT_DIR/../.." && pwd -P)"

BASELINE="${STRESS_BASELINE:-$REPO_DIR/scripts/stress-baseline.txt}"
WRITE_BASELINE="${STRESS_WRITE_BASELINE:-}"

# The scenarios e2e-stress.sh accepts for STRESS_SCENARIO. "all" is excluded on
# purpose: it chains torn-overwrite into freeze and stops at the first failure,
# so it cannot report the second when the first is one of the known-red ones.
ALL_SCENARIOS=(partial-put torn-overwrite freeze)

if [ $# -gt 0 ]; then
    SCENARIOS=("$@")
else
    SCENARIOS=("${ALL_SCENARIOS[@]}")
fi

for s in "${SCENARIOS[@]}"; do
    found=false
    for known in "${ALL_SCENARIOS[@]}"; do
        [ "$s" = "$known" ] && found=true
    done
    if [ "$found" = false ]; then
        echo "stress-gate: unknown scenario '$s' (want: ${ALL_SCENARIOS[*]})" >&2
        exit 2
    fi
done

if [ -z "$WRITE_BASELINE" ] && [ ! -f "$BASELINE" ]; then
    echo "stress-gate: baseline $BASELINE does not exist" >&2
    exit 2
fi

RESULTS=()

for scenario in "${SCENARIOS[@]}"; do
    printf '\n=== scenario: %s ===\n' "$scenario"
    if STRESS_SCENARIO="$scenario" "$SCRIPT_DIR/e2e-stress.sh"; then
        RESULTS+=("PASS|$scenario")
        printf '  %s: PASS\n' "$scenario"
    else
        RESULTS+=("FAIL|$scenario")
        printf '  %s: FAIL\n' "$scenario"
    fi
done

if [ -n "$WRITE_BASELINE" ]; then
    {
        echo "# Generated by scripts/bench/stress-gate.sh."
        echo "# Regenerate with STRESS_WRITE_BASELINE=scripts/stress-baseline.txt when a fix lands."
        printf '%s\n' "${RESULTS[@]}"
    } > "$WRITE_BASELINE"
    printf '\nwrote baseline to %s\n' "$WRITE_BASELINE"
    # Recording what predastore does today succeeded even though some of what
    # it does today is fail, so this exits clean.
    exit 0
fi

regressions=0
fixed=0
printf '\n=== gate ===\n'
for r in "${RESULTS[@]}"; do
    IFS='|' read -r status scenario <<< "$r"
    want=$(grep -F "|$scenario" "$BASELINE" | cut -d'|' -f1 | head -1)
    if [ -z "$want" ]; then
        printf '  ? %s is not in the baseline\n' "$scenario"
        continue
    fi
    if [ "$want" = PASS ] && [ "$status" = FAIL ]; then
        printf '  REGRESSION %s survived in the baseline and fails now\n' "$scenario"
        regressions=$((regressions + 1))
    elif [ "$want" = FAIL ] && [ "$status" = PASS ]; then
        fixed=$((fixed + 1))
    fi
done

if [ "$fixed" -gt 0 ]; then
    printf '\n  %d scenario(s) now pass that the baseline expects to fail. Update %s.\n' \
        "$fixed" "$BASELINE"
fi

printf '\n'
[ "$regressions" -eq 0 ]
